const [
  head,
  tail,
  middle,
  assertArraysEqual,
  assertEqual,
  assertObjectsEqual,
  countLetters,
  countOnly,
  eqArray,
  eqObjects,
  findKey,
  letterPositions,
  map,
  takeUntil,
] = [
  require("./head"),
  require("./tail"),
  require("./middle"),
  require("./assertArraysEqual"),
  require("./assertEqual"),
  require("./assertObjectsEqual"),
  require("./countLetters"),
  require("./countOnly"),
  require("./eqArray"),
  require("./eqObjects"),
  require("./findKey"),
  require("./letterPositions"),
  require("./map"),
  require("./takeUntil"),
];

module.exports = {
  head,
  tail,
  middle,
  assertArraysEqual,
  assertEqual,
  assertObjectsEqual,
  countLetters,
  countOnly,
  eqArray,
  eqObjects,
  findKey,
  letterPositions,
  map,
  takeUntil,
};
